spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /hms/api

